### ISSUE TITLE
Doesn't Recognize Region

### ISSUE THREAD

**Issue by maxwell-gregory** [jimjkelly/lambda-deploy#5]
Having issues deploying, getting NoRegionError even though region is specified
```pi@raspberrypi:~ $ lambda-deploy deploy
2016-12-26 22:28:33:INFO:botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "/usr/local/bin/lambda-deploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lambda_deploy/lambda_deploy.py", line 360, in main
    name=options.name
  File "/usr/local/lib/python2.7/dist-packages/lambda_deploy/lambda_deploy.py", line 75, in __init__
    self.client = boto3.client('lambda')
  File "/usr/local/lib/python2.7/dist-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 828, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 69, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 222, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 44, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 101, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 295, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

In my `.env.lambda`:
`AWS_DEFAULT_REGION = us-east-1`

I even hard coded region into regions.py still doesn't work

**Comment by jimjkelly** [comment]
Did you get it to work?

**Comment by maxwell-gregory** [comment]
Yea the answer was trivial so i decided not to bother anyone.  I was following a different readme tutorial from a different site and it forgot to mention adding an env file with `-e` 

Also as a side note, MAC OS brew bug with `pip install -r requirements.txt -t /path/to/project-dir` The [link](https://github.com/jimjkelly/lambda-deploy/blob/master/src/lambda_deploy/lambda_deploy.py#L144) is outdated in the error message. The [workaround](http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html) is to add a `setup.cfg` with the following:
```
[install]
prefix=
```
Maybe you just want to add this to your repo to prevent the bug from happening?

**Comment by jimjkelly** [comment]
Ah, good call.  I'll open an issue on that and get a fix out shortly.  Also, out of curiosity, what was the tutorial you were following?

Also, no bother with adding what the solution was.  We've all been there when we've googled for some error and the person closes it thinking it was trivial and we're like, "no!  what was it!"  :)
